spring:
  datasource:
    url: jdbc:postgresql://db:5432/route_signalement
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        format_sql: true

# Firebase Configuration
firebase:
  config:
    path: serviceAccountKey.json
  api:
    key: AIzaSyB-9oIDJlAiFITWf48-Xlgw4T0ByhjWRV8
  database:
    url: https://test-8f6f5-default-rtdb.firebaseio.com

# Authentication Configuration
app:
  auth:
    max-failed-attempts: 3
  session:
    duration-minutes: 60

# Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# Logging
logging:
  level:
    root: INFO
    com.example.projet: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
